pluginManagement {
    repositories {
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    // 自动下载缺失的 JDK（本机目前只有 21/25/26，1.20.1 需要 Java 17）
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'TickControl-Forge'
